Repository GenXProject/GenX.jl, pull requests merged in 2024-11, with the labels that each got.

#781 Additional constraints to prevent violation of state of charge limits in non-representative periods
  CHANGELOG.md
  Project.toml
  src/model/resources/hydro/hydro_inter_period_linkage.jl
  src/model/resources/storage/long_duration_storage.jl
  src/write_outputs/long_duration_storage/write_opwrap_lds_stor_init.jl
Labels: bug, enhancement

#785 Fix getproperty for `Vector{Resources}` to align with new array interface
  CHANGELOG.md
  Project.toml
  src/case_runners/case_runner.jl
  src/load_inputs/load_resources_data.jl
  src/model/resources/resources.jl
  src/startup/genx_startup.jl
  src/write_outputs/capacity_reserve_margin/write_reserve_margin_revenue.jl
  src/write_outputs/energy_share_requirement/write_esr_revenue.jl
  src/write_outputs/write_curtailment.jl
  src/write_outputs/write_net_revenue.jl
  src/write_outputs/write_subsidy_revenue.jl
  src/write_outputs/write_vre_stor.jl
Labels: bug

#793 Fix description of TDR setting parameters in Tutorial 1
  Project.toml
  docs/src/Tutorials/Tutorial_1_configuring_settings.md
Labels: Skip-Changelog

#797 784 bug capres flag for transmission lines does not appear to do anything
  CHANGELOG.md
  Project.toml
  docs/src/User_Guide/model_input.md
  example_systems/10_IEEE_9_bus_DC_OPF/system/Network.csv
  example_systems/1_three_zones/system/Network.csv
  example_systems/2_three_zones_w_electrolyzer/system/Network.csv
  example_systems/3_three_zones_w_co2_capture/system/Network.csv
  example_systems/4_three_zones_w_policies_slack/system/Network.csv
  example_systems/5_three_zones_w_piecewise_fuel/system/Network.csv
  example_systems/6_three_zones_w_multistage/inputs/inputs_p1/system/Network.csv
  example_systems/6_three_zones_w_multistage/inputs/inputs_p2/system/Network.csv
  example_systems/6_three_zones_w_multistage/inputs/inputs_p3/system/Network.csv
  example_systems/7_three_zones_w_colocated_VRE_storage/system/Network.csv
  example_systems/8_three_zones_w_colocated_VRE_storage_electrolyzers/system/Network.csv
  example_systems/9_three_zones_w_retrofit/system/Network.csv
  precompile/case/system/Network.csv
  test/DCOPF/system/Network.csv
  test/load_resources/test_gen_non_colocated/system/Network.csv
  test/three_zones/system/Network.csv
Labels: documentation
