Repository GenXProject/GenX.jl, pull requests merged in 2024-12, with the labels that each got.

#796 771 bugerror writing cost when we have resources that are not new build and not eligible for retirement
  CHANGELOG.md
  Project.toml
  src/write_outputs/write_costs.jl
  test/writing_outputs/test_zone_no_resources.jl
  test/writing_outputs/zone_no_resources/highs_settings.yml
  test/writing_outputs/zone_no_resources/policies/CO2_cap.csv
  test/writing_outputs/zone_no_resources/resources/Storage.csv
  test/writing_outputs/zone_no_resources/resources/Thermal.csv
  test/writing_outputs/zone_no_resources/resources/Vre.csv
  test/writing_outputs/zone_no_resources/system/Demand_data.csv
  test/writing_outputs/zone_no_resources/system/Fuels_data.csv
  test/writing_outputs/zone_no_resources/system/Generators_variability.csv
  test/writing_outputs/zone_no_resources/system/Network.csv
Labels: bug

#794 Fix demand_data path in tutorial 8
  Project.toml
  docs/src/Tutorials/Tutorial_8_outputs.md
  docs/src/Tutorials/files/t8_cap.svg
Labels: documentation, Skip-Changelog

#798 Add add_similar_to_expression! for arrays
  CHANGELOG.md
  Project.toml
  src/model/core/operational_reserves.jl
  src/model/expression_manipulation.jl
  test/expression_manipulation_test.jl
Labels: bug

#779 Update README.md & doc with development lead from Binghamton Univ
  Project.toml
  README.md
  docs/src/index.md
Labels: documentation, Skip-Changelog

#768 Doc-Page Typo Fixes
  Project.toml
  docs/src/Model_Concept_Overview/model_notation.md
  src/model/core/transmission/dcopf_transmission.jl
  src/model/core/transmission/investment_transmission.jl
  src/model/core/transmission/transmission.jl
Labels: documentation, Skip-Changelog

#801 Settings flag for new LDS constraints activation
  CHANGELOG.md
  Project.toml
  docs/src/Tutorials/Tutorial_4_model_generation.md
  docs/src/User_Guide/model_configuration.md
  example_systems/3_three_zones_w_co2_capture/resources/Storage.csv
  example_systems/3_three_zones_w_co2_capture/settings/genx_settings.yml
  src/configure_settings/configure_settings.jl
  src/model/generate_model.jl
  src/model/resources/hydro/hydro_inter_period_linkage.jl
  src/model/resources/storage/long_duration_storage.jl
Labels: enhancement
