Repository GenXProject/GenX.jl, pull requests merged in 2025-02, with the labels that each got.

#817 Clean up storage model syntax, logic
  Project.toml
  src/model/resources/storage/investment_charge.jl
  src/model/resources/storage/investment_energy.jl
  src/model/resources/storage/long_duration_storage.jl
  src/model/resources/storage/storage.jl
  src/model/resources/storage/storage_all.jl
  src/model/resources/storage/storage_asymmetric.jl
  src/model/resources/storage/storage_symmetric.jl
Labels: skip changelog

#828 Fix path manipulation bug #827
  .github/workflows/ci.yml
  .github/workflows/test_examples.yml
  CHANGELOG.md
  CITATION.cff
  Project.toml
  README.md
  docs/src/installation.md
  src/time_domain_reduction/full_time_series_reconstruction.jl
Labels: bug

#772 Add Allam cycle module
  CHANGELOG.md
  Project.toml
  docs/make.jl
  docs/src/Model_Reference/Resources/allam_cycle.md
  docs/src/Model_Reference/write_outputs.md
  docs/src/User_Guide/model_input.md
  docs/src/User_Guide/model_output.md
  example_systems/11_three_zones_w_allam_cycle_lox/README.md
  example_systems/11_three_zones_w_allam_cycle_lox/Run.jl
  example_systems/11_three_zones_w_allam_cycle_lox/policies/CO2_cap.csv
  example_systems/11_three_zones_w_allam_cycle_lox/resources/Allam_Cycle_LOX.csv
  example_systems/11_three_zones_w_allam_cycle_lox/resources/Storage.csv
  example_systems/11_three_zones_w_allam_cycle_lox/resources/Thermal.csv
  example_systems/11_three_zones_w_allam_cycle_lox/resources/Vre.csv
  example_systems/11_three_zones_w_allam_cycle_lox/settings/clp_settings.yml
  example_systems/11_three_zones_w_allam_cycle_lox/settings/cplex_settings.yml
  example_systems/11_three_zones_w_allam_cycle_lox/settings/genx_settings.yml
  example_systems/11_three_zones_w_allam_cycle_lox/settings/gurobi_settings.yml
  example_systems/11_three_zones_w_allam_cycle_lox/settings/highs_settings.yml
  example_systems/11_three_zones_w_allam_cycle_lox/settings/time_domain_reduction_settings.yml
  example_systems/11_three_zones_w_allam_cycle_lox/system/Demand_data.csv
  example_systems/11_three_zones_w_allam_cycle_lox/system/Fuels_data.csv
  example_systems/11_three_zones_w_allam_cycle_lox/system/Generators_variability.csv
  example_systems/11_three_zones_w_allam_cycle_lox/system/Network.csv
  src/load_inputs/load_resources_data.jl
  src/model/core/discharge/investment_discharge.jl
  src/model/core/fuel.jl
  src/model/generate_model.jl
  src/model/resources/flexible_ccs/allamcycle_commit.jl
  src/model/resources/flexible_ccs/allamcycle_no_commit.jl
  src/model/resources/flexible_ccs/allamcyclelox.jl
  src/model/resources/resources.jl
  src/write_outputs/write_allamcyclelox.jl
  src/write_outputs/write_capacity.jl
  src/write_outputs/write_capacityfactor.jl
  src/write_outputs/write_charge.jl
  src/write_outputs/write_net_revenue.jl
  src/write_outputs/write_outputs.jl
  src/write_outputs/write_power_balance.jl
  test/allam_cycle_lox/highs_settings.yml
  test/allam_cycle_lox/policies/CO2_cap.csv
  test/allam_cycle_lox/policies/Capacity_reserve_margin.csv
  test/allam_cycle_lox/policies/Energy_share_requirement.csv
  test/allam_cycle_lox/policies/Minimum_capacity_requirement.csv
  test/allam_cycle_lox/resources/Allam_Cycle_LOX.csv
  test/allam_cycle_lox/resources/Storage.csv
  test/allam_cycle_lox/resources/Thermal.csv
  test/allam_cycle_lox/resources/Vre.csv
  test/allam_cycle_lox/resources/policy_assignments/Resource_capacity_reserve_margin.csv
  test/allam_cycle_lox/resources/policy_assignments/Resource_energy_share_requirement.csv
  test/allam_cycle_lox/resources/policy_assignments/Resource_minimum_capacity_requirement.csv
  test/allam_cycle_lox/system/Demand_data.csv
  test/allam_cycle_lox/system/Fuels_data.csv
  test/allam_cycle_lox/system/Generators_variability.csv
  test/allam_cycle_lox/system/Network.csv
  test/allam_cycle_lox/system/Period_map.csv
  test/test_allam_cycle.jl
Labels: enhancement

#831 Fix linking of pages of storage and crm in docs
  Project.toml
  src/model/policies/cap_reserve_margin.jl
  src/model/resources/storage/long_duration_storage.jl
  src/model/resources/storage/storage.jl
  src/model/resources/storage/storage_all.jl
  src/model/resources/vre_stor/vre_stor.jl
Labels: skip changelog
